### ISSUE TITLE
Incorrect calculation of highest combination when there's only kicker.

### ISSUE THREAD

**Issue by bowenbowensun** [Merisho/tx-holdem#9]
The following hand should return the board as the combination. However, the pocket cards are included in the highestCombination. Is this a bug or am I using it incorrectly?

const pack = new Pack()
const holeCards = new Hand([
    pack.createCard('clubs', 2),
    pack.createCard('clubs', 3)
])
const board = new Hand([
    pack.createCard('spades', 4),
    pack.createCard('hearts', 5),
    pack.createCard('clubs', 10),
    pack.createCard('diamonds', 'jack'),
    pack.createCard('spades', 'queen')
])
const col = HandsCollection.createCombinations(board, holeCards).highestCombination
console.log(col._hand.cards)

prints out
`[
  Card { suit: 20, rank: 0 },
  Card { suit: 20, rank: 1 },
  Card { suit: 20, rank: 8 },
  Card { suit: 21, rank: 9 },
  Card { suit: 23, rank: 10 }
]`

which is incorrect as the pocket cards 2 and 3 is smaller than the community cards 4 and 5.

**Comment by Merisho** [comment]
@bowenbowensun Thank you for the issue.

This looks wrong, indeed. I will take a look at it in the course of the next week.

**Comment by Merisho** [comment]
The PR with the fix has been merged into master, closing the issue
